controllers:
    resource:
        path: ../src/Infrastructure/UI/Http/Controller
        namespace: App\Infrastructure\UI\Http\Controller
    type: attribute

api_v1:
    resource: ../src/Infrastructure/UI/Http/Controller/Api/V1
    type: attribute
    prefix: /api/v1

