controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v1:
    resource: ../src/Controller/Api/V1
    type: attribute
    prefix: /api/v1

